server:
  port: 8889

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: config-client

eureka:
  client:
    register-with-eureka: true
    enabled: true
    service-url:
      default_zone: http://localhost:8761/eureka/


