server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native

---

# Настройки для свойств config-server
# Профиль native - это профиль Spring, который позволяет использовать конфигурации не из Git
# В целом, общая информация по Spring cloud -> https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html
spring:
  cloud:
    config:
      server:
        native:
          search-locations: D:\JavaProjects\Microservices\my_microservices_project\service\ms-config-properties\{application}\{profile}

