spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev   # Указал активный профиль, чтобы указать URI для Feign Client в конфигурационном файле,
                  # см. ПРОЕКТ/service/ms-config-properties/client-service/dev/client-service.yml

---
spring:
  application:
    name: client-service
  config:
    import: optional:configserver:http://localhost:8888



server:
  port: 8082

eureka:
  client:
    service-url:
      default_zone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

