server:
  port: 8891

eureka:
  client:
    register-with-eureka: true
    enabled: true
    service-url:
      default_zone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

spring:
  application:
    name: test-eureka-client-feign-B