spring:
  application:
    name: client-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8082

eureka:
  client:
    service-url:
      default_zone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true