server:
  port: 4444

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureca

  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888