spring:
  application:
    name: book-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/gallerydb
  config:
    import: optional:configserver:http://localhost:8888


server:
  port: 8081

eureka:
  client:
    service-url:
      default_zone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
